version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Kolkata"
    ignore:
      - dependency-name: "vscode"

  - package-ecosystem: "npm"
    directory: "/webview"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Kolkata"   